version: "3.9"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: vacationplanner
      POSTGRES_USER: root
    volumes:
        - ./Source/Database/:/var/lib/postgresql/data
    ports:
      - 8111:5432
  
  database_service:
    build: ./Source/Database_Service
    volumes:
      - ./Source/Database_Service:/usr/src/app
    ports:
      - 5000:80
      - 5678:5678
 
  # web:
  #   build: ./Source/Front_End
  #   command: python manage.py runserver 0.0.0.0:80
  #   volumes:
  #     - ./Source/Front_End:/code
  #   ports:
  #     - 8112:80
  #   depends_on:
  #     - db