version: "3.9"
services:
  database_backend:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: vacationplanner
      POSTGRES_USER: root
    volumes:
        - ./Source/Database/:/var/lib/postgresql/data
    ports:
      - 8111:5432
  
  database_service:
    build: ./Source/Database_Service
    volumes:
      - ./Source/Database_Service:/usr/src/app
    ports:
      - 8113:80
      - 5678:5678
 
  website:
    image: php:apache
    volumes:
      - ./Source/Front_End:/var/www/html
    ports:
      - 8112:80